// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Volumes/data/code/github.com/cloudyan/monorepo-basic/node_modules/.pnpm/dumi@2.4.7_@babel+core@7.25.2_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.3_eslin_5hwlfp5gp2i3lbghdtokss6tua/node_modules/dumi/dist/client/theme-api/index.js';
export * from './meta/exports';
