export const components = {
  common: [
    '/packages/ui-father/components/button',
    // '/packages/ui-father/components/icon'
  ],
  layout: [
    '/packages/ui-father/components/auto-center',
    '/packages/ui-father/components/divider',
    '/packages/ui-father/components/grid',
    '/packages/ui-father/components/safe-area',
    '/packages/ui-father/components/space',
  ],
  navigation: [
    '/packages/ui-father/components/capsule-tabs',
    '/packages/ui-father/components/index-bar',
    '/packages/ui-father/components/jumbo-tabs',
    '/packages/ui-father/components/nav-bar',
    '/packages/ui-father/components/side-bar',
    '/packages/ui-father/components/tab-bar',
    '/packages/ui-father/components/tabs',
  ],
  dataDisplay: [
    '/packages/ui-father/components/avatar',
    '/packages/ui-father/components/card',
    '/packages/ui-father/components/collapse',
    '/packages/ui-father/components/ellipsis',
    '/packages/ui-father/components/floating-panel',
    '/packages/ui-father/components/image',
    '/packages/ui-father/components/image-viewer',
    '/packages/ui-father/components/infinite-scroll',
    '/packages/ui-father/components/list',
    '/packages/ui-father/components/page-indicator',
    '/packages/ui-father/components/steps',
    '/packages/ui-father/components/swiper',
    '/packages/ui-father/components/tag',
    '/packages/ui-father/components/water-mark',
    '/packages/ui-father/components/footer',
  ],
  dataEntry: [
    '/packages/ui-father/components/cascader',
    '/packages/ui-father/components/cascader-view',
    '/packages/ui-father/components/check-list',
    '/packages/ui-father/components/checkbox',
    '/packages/ui-father/components/form',
    '/packages/ui-father/components/input',
    '/packages/ui-father/components/picker',
    '/packages/ui-father/components/picker-view',
    '/packages/ui-father/components/radio',
    '/packages/ui-father/components/rate',
    '/packages/ui-father/components/search-bar',
    '/packages/ui-father/components/selector',
    '/packages/ui-father/components/slider',
    '/packages/ui-father/components/stepper',
    '/packages/ui-father/components/switch',
    '/packages/ui-father/components/text-area',
  ],
  feedback: [
    '/packages/ui-father/components/action-sheet',
    '/packages/ui-father/components/dialog',
    '/packages/ui-father/components/empty',
    '/packages/ui-father/components/error-block',
    '/packages/ui-father/components/loading',
    '/packages/ui-father/components/mask',
    '/packages/ui-father/components/modal',
    '/packages/ui-father/components/popover',
    '/packages/ui-father/components/popup',
    '/packages/ui-father/components/progress-bar',
    '/packages/ui-father/components/progress-circle',
    '/packages/ui-father/components/pull-to-refresh',
    '/packages/ui-father/components/result',
    '/packages/ui-father/components/skeleton',
    '/packages/ui-father/components/swipe-action',
    '/packages/ui-father/components/toast',
  ],
  guidance: [
    '/packages/ui-father/components/badge',
    '/packages/ui-father/components/notice-bar',
  ],
  other: ['/packages/ui-father/components/config-provider'],
  experimental: [
    '/guide/what-is-experimental',
    '/packages/ui-father/components/calendar',
    '/packages/ui-father/components/calendar-picker',
    '/packages/ui-father/components/calendar-picker-view',
    '/packages/ui-father/components/dropdown',
    '/packages/ui-father/components/floating-bubble',
    '/packages/ui-father/components/image-uploader',
    '/packages/ui-father/components/number-keyboard',
    '/packages/ui-father/components/passcode-input',
    '/packages/ui-father/components/result-page',
    '/packages/ui-father/components/tree-select',
    '/packages/ui-father/components/virtual-input',
    // '/packages/ui-father/components/scroll-mask',
  ],
};
